### PR TITLE
Add region mappings for Paris Reinforce models

### PR DESCRIPTION
**Pull request by danielhuppmann**
This PR adds definitions and mappings for three models in the Paris Reinforce project:
 - TIAM-Grantham: Migrated definitions and mappings from NAVIGATE project repository.
 - GCAM-PR 5.3: Migrated definitions and mappings from the NAVIGATE project
 - FORECAST v1.0: Added to EU-country mapping based oN ECEMF configuration

fyi @bapboitier

### CODE REVIEW

**Comment by bapboitier** [comment]
I also remarked that for NEMESIS and E4SMA-EU-TIMES, the non-EU country: NO - Norway; IS - Iceland for both models + CH - Switzrland for E4SMA-EU-TIMES) are not included in the mapping.

**Comment by danielhuppmann** [comment]
Thank you @bapboitier for the thorough review and catching my mistakes!

I have implemented all except for the issue that GCAM does not include Croatia in its EU representation - given the relative size of the economies and contribution to emissions, I think that it will still be helpful to have both a region that (almost) matches the "EU27 & UK" aggregate as well as a "Europe" including important non-EU countries.

**Comment by bapboitier** [comment]
Thank you @danielhuppmann for the corrections. I also found an error for the FORECAST mapping, native region for Greece is EL and not GR.

**Comment by danielhuppmann** [comment]
> Thank you @danielhuppmann for the corrections. I also found an error for the FORECAST mapping, native region for Greece is EL and not GR.

Fixed via #14

**Pull request merged**
